function [C_normal_1] = aerosurface_canard_online( ...
    mach, incidence, aspect_ratio, midchord_angle, ...
    canard_CL_Mach_input, canard_CL_alpha_input, canard_CL_data)

    aspect_ratio = aspect_ratio;
    midchord_angle = midchord_angle;

    alpha_deg = abs(rad2deg(incidence));

    mach_q = min(max(mach, canard_CL_Mach_input(1)), canard_CL_Mach_input(end));
    alpha_q = min(max(alpha_deg, canard_CL_alpha_input(1)), canard_CL_alpha_input(end));

    C_abs = interp2( ...
        canard_CL_Mach_input, ...
        canard_CL_alpha_input, ...
        canard_CL_data, ...
        mach_q, ...
        alpha_q, ...
        "linear");

    C_normal_1 = C_abs;

end