function [C_normal_1, CL_alpha] = aerosurface_canard_online( ...
    mach, incidence, ...
    canard_CL_Mach_input, canard_CL_alpha_input, canard_CL_data, canard_CL_alpha_data)

    alpha = abs(incidence);

    mach_q = min(max(mach, canard_CL_Mach_input(1)), canard_CL_Mach_input(end));
    alpha_q = min(max(alpha, canard_CL_alpha_input(1)), canard_CL_alpha_input(end));

    C_abs = interp2( ...
        canard_CL_Mach_input, ...
        canard_CL_alpha_input, ...
        canard_CL_data, ...
        mach_q, ...
        alpha_q, ...
        "linear");

    C_normal_1 = C_abs;

    CL_alpha = interp2( ...
        canard_CL_Mach_input, ...
        canard_CL_alpha_input, ...
        canard_CL_alpha_data, ...
        mach_q, ...
        alpha_q, ...
        "linear");

end
